# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c701d59ba2163f792fa2c08a31346f99"
name = "epayco credit card payment"
handle = "epayco-credit-card-payment"
application_url = "https://well-moscow-developments-herb.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "customerpayco.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://well-moscow-developments-herb.trycloudflare.com/auth/callback",
  "https://well-moscow-developments-herb.trycloudflare.com/auth/shopify/callback",
  "https://well-moscow-developments-herb.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
